# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVM0fyn-WQNnYl_xwN8Ues-0PDORpBFb
"""

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model


model = load_model('tumor_otak.h5')  


def preprocess_image(image):
    image = cv2.resize(image, (224, 224))  
    image = image / 255.0  
    return np.expand_dims(image, axis=0)  

st.title("Prediksi Tumor dari Gambar")


uploaded_file = st.file_uploader("Unggah gambar tumor", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
  
    image = cv2.imdecode(np.frombuffer(uploaded_file.read(), np.uint8), cv2.IMREAD_COLOR)
    st.image(image, caption="Gambar yang diunggah", use_column_width=True)

   
    processed_image = preprocess_image(image)

    
    prediction = model.predict(processed_image)
    predicted_class = np.argmax(prediction, axis=1)

    # Menampilkan hasil prediksi
    if(predicted[0] == 0):
        predicted_class = 'Prediksi: No (Tidak ada tumor)'
    else:
        predicted_class = 'Prediksi: Yes (Ada tumor)'
